
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deepto Shome Pritom
 */
public class AppWindow extends javax.swing.JFrame {

    /**
     * Creates new form AppWindow
     */
    public AppWindow() {
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CALCULATORButton = new javax.swing.JButton();
        LOVETESTERButton = new javax.swing.JButton();
        GPACALCULATORButton = new javax.swing.JButton();
        TicTacToeButton = new javax.swing.JButton();
        DrumButton = new javax.swing.JButton();
        PianoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Store");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(46, 134, 193));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PSP");

        CALCULATORButton.setBackground(new java.awt.Color(26, 188, 156));
        CALCULATORButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        CALCULATORButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        CALCULATORButton.setText("CALCULATOR");
        CALCULATORButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CALCULATORButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CALCULATORButton.setIconTextGap(280);
        CALCULATORButton.setInheritsPopupMenu(true);
        CALCULATORButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATORButtonActionPerformed(evt);
            }
        });

        LOVETESTERButton.setBackground(new java.awt.Color(26, 188, 156));
        LOVETESTERButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        LOVETESTERButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        LOVETESTERButton.setText("LOVE TESTER");
        LOVETESTERButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOVETESTERButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LOVETESTERButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LOVETESTERButton.setIconTextGap(278);
        LOVETESTERButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOVETESTERButtonActionPerformed(evt);
            }
        });

        GPACALCULATORButton.setBackground(new java.awt.Color(26, 188, 156));
        GPACALCULATORButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        GPACALCULATORButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        GPACALCULATORButton.setText("GPA CALCULATOR");
        GPACALCULATORButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GPACALCULATORButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        GPACALCULATORButton.setIconTextGap(225);
        GPACALCULATORButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPACALCULATORButtonActionPerformed(evt);
            }
        });

        TicTacToeButton.setBackground(new java.awt.Color(26, 188, 156));
        TicTacToeButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        TicTacToeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        TicTacToeButton.setText("Tic Tac Toe");
        TicTacToeButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TicTacToeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TicTacToeButton.setIconTextGap(300);
        TicTacToeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicTacToeButtonActionPerformed(evt);
            }
        });

        DrumButton.setBackground(new java.awt.Color(26, 188, 156));
        DrumButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        DrumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        DrumButton.setText("Drum");
        DrumButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DrumButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DrumButton.setIconTextGap(365);
        DrumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrumButtonActionPerformed(evt);
            }
        });

        PianoButton.setBackground(new java.awt.Color(26, 188, 156));
        PianoButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        PianoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qqqqq.png"))); // NOI18N
        PianoButton.setText("Piano");
        PianoButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PianoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PianoButton.setIconTextGap(365);
        PianoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PianoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LOVETESTERButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TicTacToeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GPACALCULATORButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CALCULATORButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PianoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(LOVETESTERButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CALCULATORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(GPACALCULATORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TicTacToeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DrumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PianoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOVETESTERButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOVETESTERButtonActionPerformed
        AppWindow ap = new AppWindow();
        ap.setVisible(false);
        dispose();
        
        LoveCalculator lc = new LoveCalculator();
        lc.setVisible(true);
    }//GEN-LAST:event_LOVETESTERButtonActionPerformed

    private void CALCULATORButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATORButtonActionPerformed
        AppWindow aw = new AppWindow();
        aw.setVisible(false);
        dispose();
        
        Calculator c = new Calculator();
        c.setVisible(true);
    }//GEN-LAST:event_CALCULATORButtonActionPerformed

    private void GPACALCULATORButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPACALCULATORButtonActionPerformed
        AppWindow ob = new AppWindow();
        ob.setVisible(false);
        dispose();
        
        GpaCalc ob1 = new GpaCalc();
        ob1.setVisible(true);
        
    }//GEN-LAST:event_GPACALCULATORButtonActionPerformed

    private void TicTacToeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicTacToeButtonActionPerformed
       AppWindow ob = new AppWindow();
        ob.setVisible(false);
        dispose();
        
        TicTacToy ob1 = new TicTacToy();
        ob1.setVisible(true);
        
    }//GEN-LAST:event_TicTacToeButtonActionPerformed

    private void DrumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrumButtonActionPerformed
        AppWindow ob = new AppWindow();
        ob.setVisible(false);
        dispose();
        
        Drum ob1 = new Drum();
        ob1.setVisible(true);
    }//GEN-LAST:event_DrumButtonActionPerformed

    private void PianoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PianoButtonActionPerformed
        AppWindow ob = new AppWindow();
        ob.setVisible(false);
        dispose();
        
        PianoFrame ob1 = new PianoFrame();
        ob1.setVisible(true);
    }//GEN-LAST:event_PianoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULATORButton;
    private javax.swing.JButton DrumButton;
    private javax.swing.JButton GPACALCULATORButton;
    private javax.swing.JButton LOVETESTERButton;
    private javax.swing.JButton PianoButton;
    private javax.swing.JButton TicTacToeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appwindow.png")));
    }
}
