
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deepto Shome Pritom
 */
public class GpaCalc extends javax.swing.JFrame {

    /**
     * Creates new form GpaCalc
     */
    
    private double banmarks;
    private double engmarks;
    private double mathmarks;
    private double phymarks;
    private double chemarks;
    private double biomarks;
    private double hmatmarks;
    private double rsmarks;
    private double totalmarks;
    private double bangpa;
    private double enggpa;
    private double mathgpa;
    private double phygpa;
    private double chegpa;
    private double biogpa;
    private double hmatgpa;
    private double rsgpa;
    private double totalgpa;
    private double gpa;
    private boolean pass = true;
    private JFrame frame;
    
    
    public GpaCalc() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bangla = new javax.swing.JTextField();
        physics = new javax.swing.JTextField();
        english = new javax.swing.JTextField();
        maths = new javax.swing.JTextField();
        chemistry = new javax.swing.JTextField();
        biology = new javax.swing.JTextField();
        religious = new javax.swing.JTextField();
        highmath = new javax.swing.JTextField();
        Calculate_Gpa = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BACKButton = new javax.swing.JButton();
        RESETButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result_area = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GPA Calculator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("ENTER YOUR MARKS HERE");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("BANGLA :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("MATHEMATICS : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("PHYSICS : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("ENGLISH : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("BIOLOGY : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setText("RELIGIOUS STUDIES : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel8.setText("CHEMISTRY : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel9.setText("HIGHER MATHEMATICS : ");

        bangla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                banglaKeyTyped(evt);
            }
        });

        physics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                physicsKeyTyped(evt);
            }
        });

        english.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                englishKeyTyped(evt);
            }
        });

        maths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mathsKeyTyped(evt);
            }
        });

        chemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chemistryKeyTyped(evt);
            }
        });

        biology.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                biologyKeyTyped(evt);
            }
        });

        religious.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                religiousKeyTyped(evt);
            }
        });

        highmath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                highmathKeyTyped(evt);
            }
        });

        Calculate_Gpa.setBackground(new java.awt.Color(0, 153, 0));
        Calculate_Gpa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        Calculate_Gpa.setForeground(new java.awt.Color(255, 255, 255));
        Calculate_Gpa.setText("Calculate");
        Calculate_Gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate_GpaActionPerformed(evt);
            }
        });

        RefreshButton.setBackground(new java.awt.Color(0, 153, 0));
        RefreshButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calculate_Gpa)
                        .addGap(8, 8, 8))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(highmath, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(english)
                            .addComponent(physics)
                            .addComponent(chemistry)
                            .addComponent(maths)
                            .addComponent(biology)
                            .addComponent(religious, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangla))))
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(bangla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(physics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(chemistry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(biology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(religious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(highmath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calculate_Gpa)
                    .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel10.setText("RESULT");

        BACKButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        BACKButton.setText("BACK");
        BACKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKButtonActionPerformed(evt);
            }
        });

        RESETButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        RESETButton.setText("RESET");
        RESETButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETButtonActionPerformed(evt);
            }
        });

        result_area.setEditable(false);
        result_area.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jScrollPane2.setViewportView(result_area);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BACKButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RESETButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACKButton)
                    .addComponent(RESETButton))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKButtonActionPerformed
         if(JOptionPane.showConfirmDialog(frame, "Are You Sure Want To Exit", "GPA Calculator", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {GpaCalc ob = new GpaCalc();
        ob.setVisible(false);
        dispose();
        
        AppWindow ob1 = new AppWindow();
        ob1.setVisible(true);}
    }//GEN-LAST:event_BACKButtonActionPerformed

    private void RESETButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETButtonActionPerformed
        result_area.setText(null);
    }//GEN-LAST:event_RESETButtonActionPerformed

    private void Calculate_GpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate_GpaActionPerformed
       
        bangpa = enggpa = mathgpa = phygpa = chegpa = biogpa = rsgpa = hmatgpa = 0.00;
        
        banmarks = Double.parseDouble(bangla.getText());
        engmarks = Double.parseDouble(english.getText());
        mathmarks = Double.parseDouble(maths.getText());
        phymarks = Double.parseDouble(physics.getText());
        chemarks = Double.parseDouble(chemistry.getText());
        biomarks = Double.parseDouble(biology.getText());
        rsmarks = Double.parseDouble(religious.getText());
        hmatmarks = Double.parseDouble(highmath.getText());
        
        
        if (banmarks < 33 || engmarks < 33 || mathmarks < 33 || phymarks < 33 || chemarks < 33 || biomarks < 33 || rsmarks < 33 || hmatmarks < 33)
            result_area.setText("Failed !!!");
        else
        { 
            if (banmarks >= 80 && banmarks <= 100)  bangpa += 5.00;
            else if (banmarks >= 70 && banmarks <= 79)  bangpa += 4.00;
            else if (banmarks >= 60 && banmarks <= 69)  bangpa += 3.50;
            else if (banmarks >= 50 && banmarks <= 59)  bangpa += 3.00;
            else if (banmarks >= 40 && banmarks <= 49)  bangpa += 2.00;
            else if (banmarks >= 33 && banmarks <= 39)  bangpa += 1.00;
            
            if (engmarks >= 80 && engmarks <= 100)  enggpa += 5.00;
            else if (engmarks >= 70 && engmarks <= 79)  enggpa += 4.00;
            else if (engmarks >= 60 && engmarks <= 69)  enggpa += 3.50;
            else if (engmarks >= 50 && engmarks <= 59)  enggpa += 3.00;
            else if (engmarks >= 40 && engmarks <= 49)  enggpa += 2.00;
            else if (engmarks >= 33 && engmarks <= 39)  enggpa += 1.00;
            
            if (mathmarks >= 80 && mathmarks <= 100)  mathgpa += 5.00;
            else if (mathmarks >= 70 && mathmarks <= 79)  mathgpa += 4.00;
            else if (mathmarks >= 60 && mathmarks <= 69)  mathgpa += 3.50;
            else if (mathmarks >= 50 && mathmarks <= 59)  mathgpa += 3.00;
            else if (mathmarks >= 40 && mathmarks <= 49)  mathgpa += 2.00;
            else if (mathmarks >= 33 && mathmarks <= 39)  mathgpa += 1.00;
            
            if (phymarks >= 80 && phymarks <= 100)  phygpa += 5.00;
            else if (phymarks >= 70 && phymarks <= 79)  phygpa += 4.00;
            else if (phymarks >= 60 && phymarks <= 69)  phygpa += 3.50;
            else if (phymarks >= 50 && phymarks <= 59)  phygpa += 3.00;
            else if (phymarks >= 40 && phymarks <= 49)  phygpa += 2.00;
            else if (phymarks >= 33 && phymarks <= 39)  phygpa += 1.00;
            
            if (chemarks >= 80 && chemarks <= 100)  chegpa += 5.00;
            else if (chemarks >= 70 && chemarks <= 79)  chegpa += 4.00;
            else if (chemarks >= 60 && chemarks <= 69)  chegpa += 3.50;
            else if (chemarks >= 50 && chemarks <= 59)  chegpa += 3.00;
            else if (chemarks >= 40 && chemarks <= 49)  chegpa += 2.00;
            else if (chemarks >= 33 && chemarks <= 39)  chegpa += 1.00;
            
            if (biomarks >= 80 && biomarks <= 100)  biogpa += 5.00;
            else if (biomarks >= 70 && biomarks <= 79)  biogpa += 4.00;
            else if (biomarks >= 60 && biomarks <= 69)  biogpa += 3.50;
            else if (biomarks >= 50 && biomarks <= 59)  biogpa += 3.00;
            else if (biomarks >= 40 && biomarks <= 49)  biogpa += 2.00;
            else if (biomarks >= 33 && biomarks <= 39)  biogpa += 1.00;
            
            if (rsmarks >= 80 && rsmarks <= 100)  rsgpa += 5.00;
            else if (rsmarks >= 70 && rsmarks <= 79)  rsgpa += 4.00;
            else if (rsmarks >= 60 && rsmarks <= 69)  rsgpa += 3.50;
            else if (rsmarks >= 50 && rsmarks <= 59)  rsgpa += 3.00;
            else if (rsmarks >= 40 && rsmarks <= 49)  rsgpa += 2.00;
            else if (rsmarks >= 33 && rsmarks <= 39)  rsgpa += 1.00;
            
            if (hmatmarks >= 80 && hmatmarks <= 100)  hmatgpa += 5.00;
            else if (hmatmarks >= 70 && hmatmarks <= 79)  hmatgpa += 4.00;
            else if (hmatmarks >= 60 && hmatmarks <= 69)  hmatgpa += 3.50;
            else if (hmatmarks >= 50 && hmatmarks <= 59)  hmatgpa += 3.00;
            else if (hmatmarks >= 40 && hmatmarks <= 49)  hmatgpa += 2.00;
            else if (hmatmarks >= 33 && hmatmarks <= 39)  hmatgpa += 1.00;
            
            totalmarks = banmarks + engmarks + mathmarks + phymarks + chemarks + biomarks + rsmarks + hmatmarks;
            totalgpa = bangpa + enggpa + mathgpa + phygpa + chegpa + biogpa + rsgpa + hmatgpa;
            gpa = totalgpa / 8;
            
            result_area.setText("You're Passed !!!" + "\n" +"TOTAL MARKS : " + (int)totalmarks + "\n" + "GPA: " + new DecimalFormat("##.##").format(gpa));
        }   
        
    }//GEN-LAST:event_Calculate_GpaActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        bangla.setText(null);
        english.setText(null);
        maths.setText(null);
        physics.setText(null);
        chemistry.setText(null);
        biology.setText(null);
        religious.setText(null);
        highmath.setText(null);
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void banglaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_banglaKeyTyped
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_banglaKeyTyped

    private void englishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_englishKeyTyped
       char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_englishKeyTyped

    private void mathsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathsKeyTyped
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_mathsKeyTyped

    private void physicsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_physicsKeyTyped
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_physicsKeyTyped

    private void chemistryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemistryKeyTyped
       char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_chemistryKeyTyped

    private void biologyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biologyKeyTyped
       char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_biologyKeyTyped

    private void religiousKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_religiousKeyTyped
       char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_religiousKeyTyped

    private void highmathKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highmathKeyTyped
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_highmathKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GpaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKButton;
    private javax.swing.JButton Calculate_Gpa;
    private javax.swing.JButton RESETButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextField bangla;
    private javax.swing.JTextField biology;
    private javax.swing.JTextField chemistry;
    private javax.swing.JTextField english;
    private javax.swing.JTextField highmath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maths;
    private javax.swing.JTextField physics;
    private javax.swing.JTextField religious;
    private javax.swing.JTextPane result_area;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gpacalculator.png")));
    }
}
