
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S.M. SHAHi
 */
public class LoveCalculator extends javax.swing.JFrame {

    private JFrame frame;
    double s = 0.00;
    public LoveCalculator() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        your_c_name = new javax.swing.JTextField();
        your_name = new javax.swing.JTextField();
        STARTTESTButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Love Tester");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(820, 512));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Love Tester");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 20, 330, 80);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 21)); // NOI18N
        jLabel3.setText("Type in two names and find out how much they love each other");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 760, 60);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Your Crash Name: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 260, 200, 30);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Your Name : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 190, 140, 30);

        your_c_name.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        your_c_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(your_c_name);
        your_c_name.setBounds(260, 260, 470, 30);

        your_name.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        your_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(your_name);
        your_name.setBounds(260, 190, 470, 30);

        STARTTESTButton.setBackground(new java.awt.Color(255, 0, 51));
        STARTTESTButton.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        STARTTESTButton.setText("START TEST!");
        STARTTESTButton.setBorder(null);
        STARTTESTButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STARTTESTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTTESTButtonActionPerformed(evt);
            }
        });
        jPanel1.add(STARTTESTButton);
        STARTTESTButton.setBounds(610, 320, 120, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0%");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 370, 90, 28);

        BackButton.setBackground(new java.awt.Color(255, 51, 51));
        BackButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 0, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(10, 10, 90, 29);

        jProgressBar1.setBackground(new java.awt.Color(255, 0, 0));
        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(204, 0, 0));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(70, 430, 660, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/love-hd.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 804, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void STARTTESTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTTESTButtonActionPerformed
        
        jLabel6.setText("");
        
        
        String yn = your_name.getText().toLowerCase();
        String ycn = your_c_name.getText().toLowerCase();
        
        int t1,t2,s1,s2;
        
        
        t1=0;
        for (int i=0; i<yn.length(); i++)
        {
            char a = yn.charAt(i);
        
            if (a >= 'a' || a<= 'Z')
                t1+=(int)a-96;
        }

        s1=0;
        while(t1!=0)
        {
            s1+=t1%10;
            t1/=10;
        }
        if(s1>9)
        {
            t1=s1;
            s1=0;
            while(t1!=0)
            {
                s1+=t1%10;
                t1/=10;
            }
        }

        t2=0;
        for (int i=0; i<ycn.length(); i++)
        {
            char a = ycn.charAt(i);

            if (a >= 'a' || a<= 'Z')
                t2+=(int)a-96;
        }

        s2=0;
        while(t2!=0)
        {
            s2+=t2%10;
            t2/=10;
        }
        if(s2>9)
        {
            t2=s2;
            s2=0;
            while(t2!=0)
            {
                s2+=t2%10;
                t2/=10;
            }
        }

        if(s1>s2)
            s=(double)s2*100/(double)s1;
        else
            s=(double)s1*100/(double)s2;

        
           jLabel6.setText(new DecimalFormat("##.##").format(s)+"%");
           jProgressBar1.setValue((int)s);
        
       //try
       // {
           for(int i=0; i<=s; i++)
           {
             //Thread.sleep(30);
             //jLabel6.setText(new DecimalFormat("##.##").format(i)+"%");
            // jProgressBar1.setValue(i);
           
           }
       // }
       // catch(Exception e)
            //    {
                    
           //     } 
        
    
    }//GEN-LAST:event_STARTTESTButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
         if(JOptionPane.showConfirmDialog(frame, "Are You Sure Want To Exit", "Love Tester", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            LoveCalculator ob = new LoveCalculator();
            ob.setVisible(false);
            dispose();
        
            AppWindow ob1 = new AppWindow();
            ob1.setVisible(true);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoveCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton STARTTESTButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField your_c_name;
    private javax.swing.JTextField your_name;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("love-icon.png")));
    }
}
